# ==================================================================
# Code for QCBM applied MC Generated Gamma-Gamma into Dimuon events
# This code version applies noise to simulate real quantum computer
#
# This version is designed to be scaled to use 6 qubits
#
# Project for PHSX 801 by LCVR
# ==================================================================
import numpy as np
import matplotlib.pyplot as plt
import uproot
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit_ibm_runtime import SamplerV2 as RuntimeSampler
from qiskit_ibm_runtime.fake_provider import FakeOslo
from scipy.optimize import minimize
from qiskit.quantum_info import Statevector
from datetime import datetime

plt.rcParams['text.usetex'] = True

# ==========================================
# 1. DATA INITIALIZATION
# ==========================================
qubits_per_var = 3  # 3 qubits for pT, 3 for Mass (6 qubits total, 64 states)
num_qubits = qubits_per_var * 2
bins_per_var = 2**qubits_per_var
total_bins = 2**num_qubits
num_layers = 4

# Open the ROOT file generated by tree_converter.C
file = uproot.open("starlight_output.root")
tree = file["upc"]

# Extract the transverse momentum components
px1, py1, pz1 = tree["px1"].array(library="np"), tree["py1"].array(library="np"), tree["pz1"].array(library="np")
px2, py2, pz2 = tree["px2"].array(library="np"), tree["py2"].array(library="np"), tree["pz2"].array(library="np")

muon_mass = 0.105658 # in GeV

# Calculate individual energies: E = sqrt(p^2 + m^2)
E1 = np.sqrt(px1**2 + py1**2 + pz1**2 + muon_mass**2)
E2 = np.sqrt(px2**2 + py2**2 + pz2**2 + muon_mass**2)

# Calculate pair pT
pair_px, pair_py, pair_pz = px1 + px2, py1 + py2, pz1 + pz2
pair_pt = np.sqrt(pair_px**2 + pair_py**2)

# Calculate Invariant Mass: M = sqrt(E_tot^2 - P_tot^2)
E_tot = E1 + E2
P_tot_sq = pair_px**2 + pair_py**2 + pair_pz**2
pair_mass = np.sqrt(E_tot**2 - P_tot_sq)

pt_range = [0.0, 0.15]
mass_range = [2.5, 2.8] # Example for J/psi

# Create 2D histogram
counts_2d, pt_edges, mass_edges = np.histogram2d(
    pair_pt, pair_mass,
    bins=[bins_per_var, bins_per_var],
    range=[pt_range, mass_range]
)

# Flatten the 8x8 grid into a 1D array of 64 states and normalize
target_probs = counts_2d.flatten() / np.sum(counts_2d)

print(f"Loaded {len(pair_pt)} events from STARlight.")
print(f"Target probabilities: {target_probs}")

# ==========================================
# 2. THE QUANTUM CIRCUIT (ANSATZ)
# ==========================================
# Note: This should be valid for a variety of qubits (i.e. shouldn't need to change it w.r.t. # of qubits)
def create_qcbm_ansatz(num_qubits, num_layers):
    qc = QuantumCircuit(num_qubits)
    total_params = num_qubits * (num_layers + 1)
    theta = ParameterVector('theta', total_params)

    param_idx = 0
    for i in range(num_qubits):
        qc.ry(theta[param_idx], i)
        param_idx += 1

    for layer in range(num_layers):
        for i in range(num_qubits - 1):
            qc.cx(i, i + 1)
        for i in range(num_qubits):
            qc.ry(theta[param_idx], i)
            param_idx += 1

    # Measurements removed here to allow exact Statevector simulation
    return qc

ansatz = create_qcbm_ansatz(num_qubits, num_layers)
num_params = ansatz.num_parameters
print(ansatz.draw())
ansatz.draw(output='mpl', filename='qcbm_ansatz.pdf')

# ==========================================
# 3. PHASE B: THE MMD LOSS FUNCTION
# ==========================================
def compute_2d_mixed_kernel(bins_per_var, sigmas=[0.5, 1.0, 2.0]):
    total_states = bins_per_var**2

    # Map the 1D state index (0 to 63) back to 2D grid coordinates (x, y)
    state_indices = np.arange(total_states)
    x_coords = state_indices % bins_per_var    # pT index
    y_coords = state_indices // bins_per_var   # Mass index

    # Calculate squared Euclidean distance on the 2D grid
    dx = x_coords[:, None] - x_coords[None, :]
    dy = y_coords[:, None] - y_coords[None, :]
    dist_sq_2d = dx**2 + dy**2

    # Sum the Gaussian kernels
    K = np.zeros((total_states, total_states))
    for sigma in sigmas:
        K += np.exp(-dist_sq_2d / (2.0 * sigma**2))
    return K

kernel = compute_2d_mixed_kernel(bins_per_var)

# This function is fine regardless of dimension
def mmd_loss(quantum_probs, target_probs, kernel_matrix):
    P = target_probs.reshape(-1, 1)
    Q = quantum_probs.reshape(-1, 1)
    term1 = np.dot(P.T, np.dot(kernel_matrix, P))
    term2 = -2.0 * np.dot(P.T, np.dot(kernel_matrix, Q))
    term3 = np.dot(Q.T, np.dot(kernel_matrix, Q))
    return max((term1 + term2 + term3).item(), 0.0)

# ==========================================
# 4. EXACT STATEVECTOR OPTIMIZATION
# ==========================================
loss_history = []

def objective_function(theta_vals):
    # Bind parameters to the unmeasured circuit
    bound_circuit = ansatz.assign_parameters(theta_vals)

    # Calculate exact mathematical probabilities (zero shot noise)
    quantum_probs = Statevector(bound_circuit).probabilities()

    loss = mmd_loss(quantum_probs, target_probs, kernel)
    loss_history.append(loss)

    if len(loss_history) % 50 == 0:
        print(f"Iteration {len(loss_history)} | Loss: {loss:.6f}")

    return loss

print(f"Starting exact optimization with {num_params} parameters...")
initial_theta = np.random.rand(num_params) * 2 * np.pi

# SLSQP gradient-based optimizer converges efficiently on the smooth exact loss landscape (used vs COBLYA)
result = minimize(
    objective_function,
    initial_theta,
    method='SLSQP',
    options={'maxiter': 500, 'ftol': 1e-6}
)

optimal_theta = result.x
print(f"\nOptimization finished! Final Loss: {result.fun:.6f}")

# ==========================================
# 5. NOISY HARDWARE EVALUATION
# ==========================================
fake_backend = FakeOslo()
noisy_sampler = RuntimeSampler(mode=fake_backend)
print(f"\nTranspiling circuit for {type(fake_backend).backend_name} and running noisy simulation...")
shots = 10000

# 1. Create a copy of the ansatz and add measurement gates for hardware execution
measured_ansatz = ansatz.copy()
measured_ansatz.measure_all()

# 2. Transpile the MEASURED ansatz
pm = generate_preset_pass_manager(optimization_level=1, backend=fake_backend)
isa_ansatz = pm.run(measured_ansatz)

# 3. Execute the optimal weights on the noisy simulator
noisy_job = noisy_sampler.run([(isa_ansatz, optimal_theta)], shots=shots)
noisy_result = noisy_job.result()[0]

classical_reg = list(noisy_result.data.keys())[0]
noisy_counts = getattr(noisy_result.data, classical_reg).get_counts()

final_noisy_probs = np.zeros(total_bins)
for bitstring, count in noisy_counts.items():
    state = int(bitstring, 2)
    final_noisy_probs[state] = count / shots

# 4. Generate the Ideal baseline plot using exact Statevector math
final_noiseless_probs = Statevector(ansatz.assign_parameters(optimal_theta)).probabilities()

# ==========================================
# 6. VISUALIZATION
# ==========================================
# Reshape the 1D arrays back into 2D grids
target_grid = target_probs.reshape(bins_per_var, bins_per_var)
ideal_qcbm_grid = final_noiseless_probs.reshape(bins_per_var, bins_per_var)
noisy_qcbm_grid = final_noisy_probs.reshape(bins_per_var, bins_per_var)

fig, axes = plt.subplots(1, 4, figsize=(20, 5))

# Plot 1: Loss History
axes[0].plot(loss_history, color='navy', linewidth=2)
axes[0].set_title("QCBM Training: 2D MMD Loss")
axes[0].set_yscale('log')
axes[0].grid(True, linestyle='--', alpha=0.7)

# Heatmap parameters
extent = [pt_range[0], pt_range[1], mass_range[0], mass_range[1]]
cmap = 'viridis'

# Plot 2: Classical Target
im1 = axes[1].imshow(target_grid.T, origin='lower', extent=extent, aspect='auto', cmap=cmap)
axes[1].set_title("STARlight Target")
axes[1].set_xlabel("\(p_T\) (GeV/c)")
axes[1].set_ylabel("Mass (GeV/\(c^2\))")

# Plot 3: Ideal QCBM
im2 = axes[2].imshow(ideal_qcbm_grid.T, origin='lower', extent=extent, aspect='auto', cmap=cmap)
axes[2].set_title("Ideal QCBM (Statevector)")
axes[2].set_xlabel("\(p_T\) (GeV/c)")

# Plot 4: Noisy QCBM
im3 = axes[3].imshow(noisy_qcbm_grid.T, origin='lower', extent=extent, aspect='auto', cmap=cmap)
axes[3].set_title(f"Noisy QCBM ({type(fake_backend).backend_name})")
axes[3].set_xlabel("\(p_T\) (GeV/c)")

fig.colorbar(im1, ax=axes, orientation='vertical', fraction=0.02, pad=0.04)
#plt.tight_layout()
timestamp = datetime.now().strftime("%Y%m%d_%H%M")
filename = f"6qubit_plot_{timestamp}.png"
plt.savefig(filename)
plt.show()
