# ==================================================================
# Code for QCBM applied MC Generated Gamma-Gamma into Dimuon events
# This code version applies noise to simulate real quantum computer
# Project for PHSX 801 by LCVR
# ==================================================================
import numpy as np
import matplotlib.pyplot as plt
import uproot
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit_ibm_runtime import SamplerV2 as RuntimeSampler
from qiskit_ibm_runtime.fake_provider import FakeManilaV2
from scipy.optimize import minimize
from qiskit.quantum_info import Statevector
from datetime import datetime

plt.rcParams['text.usetex'] = True

# ==========================================
# 1. DATA INITIALIZATION
# ==========================================
num_qubits = 4
num_bins = 2**num_qubits
num_layers = 4  # Increased depth for greater expressivity (OG is 2)

# Open the ROOT file generated by tree_converter.C
file = uproot.open("starlight_output.root")
tree = file["upc"]

# Extract the transverse momentum components
px1 = tree["px1"].array(library="np")
py1 = tree["py1"].array(library="np")
px2 = tree["px2"].array(library="np")
py2 = tree["py2"].array(library="np")

# Calculate the parent vector meson's transverse momentum (pT)
pair_px = px1 + px2
pair_py = py1 + py2
pair_pt = np.sqrt(pair_px**2 + pair_py**2)

# Define the physical range for the pT distribution (in GeV/c)
pt_min = 0.0
pt_max = 0.15

# Discretize the continuous pT data into 16 discrete bins
counts, _ = np.histogram(pair_pt, bins=num_bins, range=(pt_min, pt_max))

# Normalize the counts to create a quantum probability distribution
target_probs = counts / np.sum(counts)

print(f"Loaded {len(pair_pt)} events from STARlight.")
print(f"Target probabilities: {target_probs}")

# ==========================================
# 2. THE QUANTUM CIRCUIT (ANSATZ)
# ==========================================
# Note: This should be valid for a variety of qubits (i.e. shouldn't need to change it w.r.t. # of qubits)
def create_qcbm_ansatz(num_qubits, num_layers):
    qc = QuantumCircuit(num_qubits)
    total_params = num_qubits * (num_layers + 1)
    theta = ParameterVector('θ', total_params)

    param_idx = 0
    for i in range(num_qubits):
        qc.ry(theta[param_idx], i)
        param_idx += 1

    for layer in range(num_layers):
        for i in range(num_qubits - 1):
            qc.cx(i, i + 1)
        for i in range(num_qubits):
            qc.ry(theta[param_idx], i)
            param_idx += 1

    # Measurements removed here to allow exact Statevector simulation
    return qc

ansatz = create_qcbm_ansatz(num_qubits, num_layers)
num_params = ansatz.num_parameters
print(ansatz.draw())

# ==========================================
# 3. THE MMD LOSS FUNCTION
# ==========================================
def compute_mixed_kernel(num_bins, sigmas=[0.25, 0.5, 1.0, 2.0]):
    # Precomputes a mixture of Gaussian kernels for better MMD gradients.
    x = np.arange(num_bins)
    dist_sq = (x[:, None] - x[None, :]) ** 2

    # Sum the kernels for all provided sigmas
    K = np.zeros((num_bins, num_bins))
    for sigma in sigmas:
        K += np.exp(-dist_sq / (2.0 * sigma ** 2))
    return K

kernel = compute_mixed_kernel(num_bins)

def mmd_loss(quantum_probs, target_probs, kernel_matrix):
    P = target_probs.reshape(-1, 1)
    Q = quantum_probs.reshape(-1, 1)
    term1 = np.dot(P.T, np.dot(kernel_matrix, P))
    term2 = -2.0 * np.dot(P.T, np.dot(kernel_matrix, Q))
    term3 = np.dot(Q.T, np.dot(kernel_matrix, Q))
    return max((term1 + term2 + term3).item(), 0.0)

# ==========================================
# 4. EXACT STATEVECTOR OPTIMIZATION
# ==========================================
loss_history = []

def objective_function(theta_vals):
    # Bind parameters to the unmeasured circuit
    bound_circuit = ansatz.assign_parameters(theta_vals)

    # Calculate exact mathematical probabilities (zero shot noise)
    quantum_probs = Statevector(bound_circuit).probabilities()

    loss = mmd_loss(quantum_probs, target_probs, kernel)
    loss_history.append(loss)

    if len(loss_history) % 50 == 0:
        print(f"Iteration {len(loss_history)} | Loss: {loss:.6f}")

    return loss

print(f"Starting exact optimization with {num_params} parameters...")
initial_theta = np.random.rand(num_params) * 2 * np.pi

# SLSQP gradient-based optimizer converges efficiently on the smooth exact loss landscape (used vs COBLYA)
result = minimize(
    objective_function,
    initial_theta,
    method='SLSQP',
    options={'maxiter': 500, 'ftol': 1e-6}
)

optimal_theta = result.x
print(f"\nOptimization finished! Final Loss: {result.fun:.6f}")

# ==========================================
# 5. NOISY HARDWARE EVALUATION
# ==========================================
# FakeManilaV2 has 5 Qubits
print("\nTranspiling circuit for FakeManilaV2 and running noisy simulation...")
fake_backend = FakeManilaV2()
noisy_sampler = RuntimeSampler(mode=fake_backend)
shots = 10000 # Increase this in the future

# 1. Create a copy of the ansatz and add measurement gates for hardware execution
measured_ansatz = ansatz.copy()
measured_ansatz.measure_all()

# 2. Transpile the MEASURED ansatz
pm = generate_preset_pass_manager(optimization_level=1, backend=fake_backend)
isa_ansatz = pm.run(measured_ansatz)

# 3. Execute the optimal weights on the noisy simulator
noisy_job = noisy_sampler.run([(isa_ansatz, optimal_theta)], shots=shots)
noisy_result = noisy_job.result()[0]

classical_reg = list(noisy_result.data.keys())[0]
noisy_counts = getattr(noisy_result.data, classical_reg).get_counts()

final_noisy_probs = np.zeros(num_bins)
for bitstring, count in noisy_counts.items():
    state = int(bitstring, 2)
    final_noisy_probs[state] = count / shots

# 4. Generate the Ideal baseline plot using exact Statevector math
final_noiseless_probs = Statevector(ansatz.assign_parameters(optimal_theta)).probabilities()

# ==========================================
# 6. Plotting
# ==========================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

# Plot 1: Loss History
ax1.plot(loss_history, color='navy', linewidth=2)
ax1.set_title("QCBM Training: Exact MMD Loss Convergence")
ax1.set_xlabel("Optimizer Iterations")
ax1.set_ylabel("MMD Loss")
ax1.set_yscale('log')
ax1.grid(True, linestyle='--', alpha=0.7)

# Plot 2: Target vs Noiseless vs Noisy
bin_edges = np.arange(num_bins + 1)
ax2.stairs(target_probs, bin_edges, fill=True, color='gray', alpha=0.3, label="STARlight Target")
ax2.stairs(final_noiseless_probs, bin_edges, color='navy', linewidth=2, linestyle='--', label="Ideal QCBM")
ax2.stairs(final_noisy_probs, bin_edges, color='crimson', linewidth=2.5, label="Noisy QCBM (FakeManila)")

ax2.set_title("Phase Space Output: Ideal vs Hardware Noise")
ax2.set_xlabel("State Index (Mapping to $p_{T}$ bins)")
ax2.set_ylabel("Probability")
ax2.set_xticks(np.arange(0, 16, 2))
ax2.legend()
ax2.grid(True, linestyle='--', alpha=0.3)

plt.tight_layout()
timestamp = datetime.now().strftime("%Y%m%d_%H%M")
filename = f"plot_{timestamp}.png"
plt.savefig(filename)
plt.show()
